config/routes.rb
Rails.application.routes.draw do
  
  root to: 'welcome#index'

  resources :user_sessions

  get 'login' => 'user_sessions#new', as: :login
  post 'logout' => 'user_sessions#destroy', as: :logout

  namespace :student do
    root to: 'welcome#index'
  end

  namespace :teacher do
    root to: 'welcome#index'
  end

  namespace :custodian do
    root to: 'welcome#index'
  end

  namespace :admin do
    root to: 'welcome#index'
  end

  namespace :multirole do
    root to: 'welcome#index'    
  end

  namespace :api, defaults: { format: :json} do
    get 'school', to: 'config#school'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/setting.rb
# RailsSettings Model
class Setting < RailsSettings::Base
  source Rails.root.join("config/app.yml")

  # When config/app.yml has changed, you need change this prefix to v2, v3 ... to expires caches
  # cache_prefix { "v1" }
end

app/models/user.rb
class User < ApplicationRecord
  authenticates_with_sorcery!

    ROLE_KINDS = %w[
        student
        teacher
        custodian
        admin
    ].freeze

    serialize :roles, Array

    def add_role(role)
        new_roles = roles.push(role).uniq
        filtered_roles = new_roles.select { |r| ROLE_KINDS.include?(r) }
        update(roles: filtered_roles)
    end
    
    def remove_role(role)
        filtered_roles = roles.reject { |r| r == role }
        update(roles: filtered_roles)
    end

    def student?
        roles.include?('student')
    end
    
    def teacher?
        roles.include?('teacher')
    end

    def custodian?
        roles.include?('custodian')
    end

    def admin?
        roles.include?('admin')
    end

    def multirole?
        roles.size > 1
    end

    def full_name
        "#{first_name} #{last_name}"
    end
end

app/controllers/admin/base_controller.rb
module Admin
    class BaseController < ApplicationController
        layout 'admin'
        before_action -> { raise 'You are not admin' unless current_user.admin? }
    end
end
  

app/controllers/admin/welcome_controller.rb
module Admin
    class WelcomeController < BaseController
        def index
        end
    end
end
  

app/controllers/api/base_controller.rb
module Api

    class BaseController < ApplicationController
        layout false
    end

end

app/controllers/api/config_controller.rb
module Api

    class ConfigController < ApplicationController
        def school
            json = {
                school: {
                    school_title: Setting.school_title
                }
            }
            
            render json: json
        end
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :require_login

    private
    def not_authenticated
        redirect_to login_path, alert: "Please login first"
    end
end

app/controllers/custodian/base_controller.rb
module Custodian
    class BaseController < ApplicationController
        layout 'custodian'
        before_action -> { raise 'You are not parent' unless current_user.custodian? }
    end
end
  

app/controllers/multirole/base_controller.rb
module Multirole
    class BaseController < ApplicationController
        layout 'multirole'
        before_action -> { raise 'You are not multirole' unless current_user.multirole? }
    end
end
  

app/controllers/multirole/welcome_controller.rb
module Multirole
    class WelcomeController < BaseController
        def index
        end
    end
end

app/controllers/student/base_controller.rb
module Student
    class BaseController < ApplicationController
        layout 'student'
        before_action -> { raise 'You are not student' unless current_user.student? }
    end
end
  

app/controllers/teacher/base_controller.rb
module Teacher
    class BaseController < ApplicationController
        layout 'teacher'
        before_action -> { raise 'You are not teacher' unless current_user.teacher? }
    end
end
  

app/controllers/user_sessions_controller.rb
class UserSessionsController < ApplicationController

  skip_before_action :require_login, only: [:index, :new, :create]

  def new
    @user = User.new
  end

  def create
    if @user = login(params[:iin], params[:password])
      role_selector = RoleSelector.new
      role_selector
        .on(:multirole) { redirect_to multirole_root_path }
        .on(:administrator) { redirect_to admin_root_path }
        .on(:student) { redirect_to student_root_path }
        .on(:custodian) { redirect_to custodian_root_path }
        .on(:none) { redirect_to no_role_root_path }
      role_selector.call(@user.roles)
    else
      flash.now[:alert] = 'Login failed'
      render action: 'new'
    end
  end

  def destroy
    logout
    redirect_to(:users, notice: 'Logged out!')
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/user_sessions_helper.rb
module UserSessionsHelper
end

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'admin' %>
  </head>

  <body>
    <div id="app"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/custodian.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'custodian' %>
  </head>

  <body>
    <div id="app"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/multirole.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/student.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'student' %>
  </head>

  <body>
    <div id="app"></div>
    <%= yield %>
  </body>
</html>

app/views/layouts/teacher.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Schooms</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= javascript_pack_tag 'teacher' %>
  </head>

  <body>
    <div id="app"></div>
    <%= yield %>
  </body>
</html>

app/views/multirole/welcome/index.html.erb
<ul>
    <li>
        <% current_user.roles.each do |role| %>
            <%= link_to role, send("#{role}_root_path") %>
        <% end %>
    </li>
</ul>

app/views/user_sessions/_form.html.erb
<%= form_tag user_sessions_path, :method => :post do %>
  <div class="field">
    <%= label_tag :iin %><br />
    <%= text_field_tag :iin %>
  </div>
  <div class="field">
    <%= label_tag :password %><br />
    <%= password_field_tag :password %>
  </div>
  <div class="actions">
    <%= submit_tag "Login" %>
  </div>
<% end %>

app/views/user_sessions/create.html.erb
<h1>UserSessions#create</h1>
<p>Find me in app/views/user_sessions/create.html.erb</p>

app/views/user_sessions/destroy.html.erb
<h1>UserSessions#destroy</h1>
<p>Find me in app/views/user_sessions/destroy.html.erb</p>

app/views/user_sessions/new.html.erb
<h1>Login</h1>

<%= render 'form' %>

<%= link_to 'Back', user_sessions_path %>